loki:
  persistence:
    enabled: false
  replication_factor: 1
  storage:
    type: boltdb-shipper
grafana:
  enabled: true
  adminPassword: admin
prometheus:
  enabled: true
  alertmanager:
    enabled: true
promtail:
  enabled: true
